name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t waistdeepwooden/react-test-up -f ./client/Dockerfile-dev ./client
      - run: docker run -e CI=true waistdeepwooden/react-test-up npm test

      - run: docker build -t waistdeepwooden/multi-client-up ./client
      - run: docker build -t waistdeepwooden/multi-nginx-up ./nginx
      - run: docker build -t waistdeepwooden/multi-server-up ./server
      - run: docker build -t waistdeepwooden/multi-worker-up ./worker

      - run: docker push waistdeepwooden/multi-client-up
      - run: docker push waistdeepwooden/multi-nginx-up
      - run: docker push waistdeepwooden/multi-server-up
      - run: docker push waistdeepwooden/multi-worker-up

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip